routes:
    - route: "^.+\\.(css|svg|ttf)$"
      headers:
        Cache-Control: "public, must-revalidate, proxy-revalidate, max-age=0"
      gzip: true
    - route: "^.+\\.(png|jpg|jpeg|ico)$"
      headers:
        Cache-Control: "public, must-revalidate, proxy-revalidate, max-age=0"
      gzip: true
    - route: "^.+\\.(html|xml|json|js)$"
      headers:
        Cache-Control: "public, must-revalidate, proxy-revalidate, max-age=0"
      gzip: true
    - route: "robots\\.txt$"
      headers:
        Content-Type: "text/plain; charset=utf-8"
