# Site settings
baseurl = "https://ketouem.com" #without ending slash
languageCode = "en-us"
title = "Ketouem - Cyril Thomas"
theme = "hugo-identity-theme"
themesDir = "./themes"
enableRobotsTXT = true

# Disable unnecessary kinds
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "404"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-107116907-1"

[params]

  description = "Senior backend software engineer"

  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance

  # Site icons
  # favicon_ico = "favicon.ico"
  # favicon_ico_sizes = "16x16 32x32"
  # appleicon = "apple.png"

  # Additional options to supplement icons served
  favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  custom_js  = ["js/githubRibbon.js"]
  #custom_css = ["background.css", "icons.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  #custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Cyril Thomas"
    # Avatars can be written to images/avatars/
    avatar = "cyril.jpg"
    position = "[Senior Software Engineer @ Enovacom - Surycat](https://www.enovacom.fr/solutions/enovacom-surycat-alerting.html)"
    livesIn = "[Boulogne-Billancourt, France](https://www.google.fr/maps/place/Boulogne-Billancourt/@48.8374891,2.2253054,14z)"
    scope = [
        "Backend software engineer",
        "DevOps enthusiast"
      ]
    biography = """Jack of all IT related trades, with main focus on:

    - microservices
    - cloud infrastructure
    - development tooling
    - CI & CD pipelines"""

  # Contact form settings

  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "ketouem@gmail.com"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    enable = true
    title = "Let's Get in Touch!"
    namePlaceholder = "Name"
    emailPlaceholder = "Email"
    messagePlaceholder = "Message"
    buttonText = "Send !"
    success = "Thank you for reaching out to me !"
    error = "Message could not be send. Please contact me at ketouem[at]gmail[dot]com"

    # Google invisible captcha
    #[params.contact.captcha]
    #  sitekey = ""


    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    #  name = "someID"
    #  value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  # You may change these with your social links or add others

  [[params.social]]
    title = "CV"
    icon = "fa-file-pdf-o"
    link = "https://public-dist.s3.amazonaws.com/cv.pdf"
    target = "_blank"

  [[params.social]]
    title = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://fr.linkedin.com/in/0cyrilthomas"
    target = "_blank"

  [[params.social]]
    title = "GitHub"
    icon = "fa-github"
    link = "https://github.com/Ketouem"
    target = "_blank"

  [[params.social]]
    title = "Stack Overflow"
    icon = "fa-stack-overflow"
    link = "https://stackoverflow.com/users/1629755/ketouem"
    target = "_blank"

  [[params.social]]
    title = "Twitter"
    icon = "fa-twitter"
    link = "https://twitter.com/Ketouem"
    target = "_blank"

  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Cyril Thomas"

  # Page license
  # [params.license]
  #   link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
  #   name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"
  [[params.credits]]
    # Title is used as URL text
    title = "Hugo"
    # Text will be used to explain the credit
    text = "Made with ♥ and"
    link = "https://gohugo.io"
  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="
