# Site settings
baseurl = "https://ketouem.com" #without ending slash
languageCode = "en-us"
title = "Ketouem - Cyril Thomas - Senior Backend Software Engineer / DevOps"
theme = "hugo-uilite"
themesDir = "./themes"
enableRobotsTXT = true

# Disable unnecessary kinds
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS"]

[params]
    gaMeasurementID = "G-TMZP4VXPET"
