version: 2.0

defaults: &defaults
  docker:
    - image: golang:1.9-alpine

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Hugo & s3deploy
          command: |
            set -ex &&
            apk add --no-cache wget make git &&
            wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.27.1/hugo_0.27.1_Linux-64bit.tar.gz &&
            tar -xzf /tmp/hugo.tar.gz -C /tmp &&
            go get -v github.com/bep/s3deploy &&
            ln -s /tmp/hugo /usr/local/bin/hugo
      - run:
          name: Build site
          command: make install && make build
      - run:
          name: Check built site
          command: test -e site/public/index.html
      - run:
          name: Deploy to bucket
          command: s3deploy -v -bucket ketouem.com -source site/public/ -region=$AWS_DEFAULT_REGION -secret=$AWS_SECRET_ACCESS_KEY -key=$AWS_ACCESS_KEY_ID
      - store_artifacts:
          path: site/public
